on:
  workflow_call:
    inputs:
      dockerfile-context:
        description: "Path to dir containing Dockerfile to build"
        required: true
        type: string
      image-tags:
        description: "Docker image tags"
        required: true
        type: string
      build-args:
        description: "Docker build args"
        required: false
        type: string
jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push Image"
        run: |
          docker build ${{ inputs.build-args }} ${{ inputs.dockerfile-context }} --tag ghcr.io/sleepysloth17/${{ inputs.image-tags }}
          docker push ghcr.io/sleepysloth17/${{ inputs.image-tags }}
