name: Test projects
on: [push]
jobs:
  Test-Account-Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Run Maven test for the account backend
        working-directory: ./backend/account
        run: mvn --batch-mode --update-snapshots test
  Test-Transaction-Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Run Maven test for the transaction backend
        working-directory: ./backend/transaction
        run: mvn --batch-mode --update-snapshots test
  Lint-And-Test-Angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./frontend/
        run: npm ci
      - name: Run linter
        working-directory: ./frontend/
        run: npm run lint
      - name: Run tests
        working-directory: ./frontend/
        run: npm run test:ci
